name: Auto merge dependabot pull requests

on:
  pull_request:
    branches:
    - master
  push:

jobs:
  comment_merge_request:
    runs-on: ubuntu-latest

    steps:
    - uses: satackey/action-automerge-dependabot-pr
#       if: github.actor == 'dependabot[bot]'
      with:
        github-token: ${{ secrets.ACCESS_TOEKN_AUTO_MERGE_DEPENDABOT_PR_BOT }}
